# Generated by Django 3.2.11 on 2022-03-16 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('car_make', models.CharField(max_length=250)),
                ('car_model', models.CharField(max_length=250)),
                ('year_made', models.CharField(max_length=20)),
                ('kms_bought', models.CharField(blank=True, max_length=100)),
                ('kms_sold', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=250)),
                ('comments', models.CharField(blank=True, max_length=500)),
                ('cars_logo', models.FileField(upload_to='')),
                ('rego', models.CharField(blank=True, max_length=10)),
                ('when_sold', models.CharField(blank=True, max_length=10)),
                ('current_car', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('colour', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_car', 'car_make'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_serv', models.DateField()),
                ('next_serv', models.DateField()),
                ('serv_by', models.CharField(max_length=20)),
                ('serv_url', models.URLField(blank=True)),
                ('serv_phone', models.CharField(blank=True, max_length=20)),
                ('serv_details', models.CharField(blank=True, max_length=500)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourcarsapp.cars')),
            ],
        ),
        migrations.CreateModel(
            name='CarsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimage', models.ImageField(upload_to='')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourcarsapp.cars')),
            ],
        ),
    ]
